resolver 34.118.224.10 valid=10s;
resolver_timeout 5s;

server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/images {
        set $upstream_image image-service.default.svc.cluster.local:3001;
        proxy_pass http://$upstream_image;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    location /api/catalogue {
        set $upstream_catalogue catalogue-service.default.svc.cluster.local:3002;
        proxy_pass http://$upstream_catalogue;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    location /api/stats {
        set $upstream_stats stats-service.default.svc.cluster.local:3003;
        proxy_pass http://$upstream_stats;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
}